version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: on-failure
    environment:
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_URL: jdbc:postgresql://keycloak-db/${KEYCLOAK_DB_DATABASE}
      KC_DB: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    command:
      - start-dev
    depends_on:
      - keycloak-db
#    networks:
#      - trainings_network
#      - keycloak_network

  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      POSTGRES_DB: ${KEYCLOAK_DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
#    networks:
#      - keycloak_network

  trainings-db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${APP_DB_USERNAME}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD:-secret}
      POSTGRES_DB: ${APP_DB_DATABASE}
    volumes:
      - trainingsData:/var/lib/postgresql/data
#    networks:
#      - trainings_network
    ports:
      - '${APP_DB_PORT:-5432}:5432'

  backend-app:
    image: training-backend-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://trainings-db:5432/${APP_DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${APP_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${APP_DB_PASSWORD:-secret}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_RESOURCE: ${KEYCLOAK_RESOURCE}
#      KEYCLOAK_PUBLIC_CLIENT: ${KEYCLOAK_PUBLIC_CLIENT:-true}
      KEYCLOAK_HOST_URL: ${KEYCLOAK_HOST_URL}
      KEYCLOAK_HTTP_MODE: ${KEYCLOAK_HTTP_MODE}
    depends_on:
      - trainings-db
      - keycloak
    ports:
      - '8080:8080'
#    networks:
#      - trainings_network
#      - keycloak_network


#
#networks:
#  trainings_network:
#    driver: bridge
#  keycloak_network:
#    driver: bridge

volumes:
  pgdata:
  trainingsData:
